all:
	lua 1.lua 2>/dev/null
	lua 2.lua 2>/dev/null
	lua multi.lua 2>/dev/null
	lua cycle.lua 2>/dev/null
	lua height.lua 2>/dev/null
	lua call.lua 2>/dev/null
	lua expr.lua 2>/dev/null
	lua meta.lua 2>/dev/null
